# Example configs to help with development.
# Mission Bay, SF

config:

  sheet_id: 1Z1Yh__KTKWY6WT1OfIWQS2zB44-cZmLtFfqj-qjYxbQ

  scraping_params:
    zipcodes:
      - 94158
    
    min_bedrooms: 1
    max_bedrooms: 2

    min_price: 0
    max_price: 4000