# Fremont & Ballard in Seattle

config:

  spreadsheet_id: '1wfZPDoTCntmDU80isbjbbjhrATx7Kpk62ZD4Ai6UdTQ'

  scraping_params:
    
    scrapers:
      - apartments.com

    zipcodes:

      # Seattle zipcodes
      - 98103  # Fremont, Green Lake
      - 98107  # Ballard
    
    min_bedrooms: 1
    max_bedrooms: 3

    min_price: 0
    max_price: 4500